apiVersion: apps/v1        
kind: Deployment           
metadata:
  name: cetech              

spec:
  replicas: 2
  selector:
    matchLabels:
      role: cetech
  template:
    metadata:
      labels:
        role: cetech
    spec:
      containers:
      - name: cetech
        image: mariana1203/crud-plantas:latest 
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:admin1234@dbpostgres/cetech"
        ports:
        - containerPort: 5000 

---
apiVersion: v1             # Versión de la API para recursos tipo Service
kind: Service              # Tipo de recurso: Service
metadata:
  name: cetech              # Nombre del Service

spec:
  type: NodePort           # Tipo de Service que expone el puerto del pod en el puerto de un nodo del clúster
  ports:
  - port: 5000             # Puerto que expone el servicio dentro del clúster
    targetPort: 5000       # Puerto al que debe redirigirse el tráfico dentro del pod
    nodePort: 30001        # Puerto del nodo (máquina física o virtual) que se utilizará para exponer la app externamente
  selector:
    role: cetech            # El servicio enviará tráfico a los pods que tengan esta etiqueta

---

# Base de datos
apiVersion: apps/v1        
kind: Deployment           
metadata:
  name: dbpostgres              

spec:
  replicas: 1
  selector:
    matchLabels:
      role: dbpostgres
  template:
    metadata:
      labels:
        role: dbpostgres
    spec:
      containers:
      - name: dbpostgres
        image: postgres:16.8
        env:
        - name: POSTGRES_DB
          value: "cetech"
        - name: POSTGRES_PASSWORD
          value: "admin1234"
        ports:
        - containerPort: 5432 

---
#Service para la base de datos
apiVersion: v1           
kind: Service            
metadata:
  name: dbpostgres            
spec:
  ports:
  - port: 5432        # Puerto expuesto por el Service
    targetPort: 5432  # Puerto del contenedor al que se debe redirigir el tráfico
  selector:
    role: dbpostgres   